[package]
name = "redis"
version = "0.1.0"
authors = ["matth"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.19.0"

[dev-dependencies]

